### ISSUE TITLE
Exception thrown in the destructor

### ISSUE THREAD

**Issue by svtesan** [OpenMAMA/OpenMAMA#34] opened 2015-10-13 00:17 UTC
MamaTransport::~MamaTransport (void)
     {
         if (mPimpl)
         {
    if ( mamaInternal_getCatchCallbackExceptions() && mPimpl->mCallback)
     {
     delete mPimpl->mCallback;
     }
             if (mPimpl->mDeleteCTransport)
             {
                 =>mamaTry (mamaTransport_destroy (mTransport)); <=
             }
             delete mPimpl;
             mPimpl = NULL;
         }
     }

We should just log and not throw an exception.

**Comment by fquinner** [comment] 2016-07-22 18:43
Duplicate of #83

**Closed by fquinner** 2016-07-22 18:43 UTC
Labels: bug
